INSERT INTO book_projet.author (author_id, surname, name, country_id)
VALUES
  (0, 'Hugo', 'Victor', 0),
  (1, 'Dumas', 'Alexandre', 0),
  (2, 'Camus', 'Albert', 0),
  (3, 'Orwell', 'George', 9),
  (4, 'Hemingway', 'Ernest', 4),
  (5, 'Austen', 'Jane', 9),
  (6, 'Tolkien', 'J.R.R.', 9),
  (7, 'Verne', 'Jules', 0),
  (8, 'Rowling', 'J.K.', 9),
  (9, 'Murakami', 'Haruki', 5),
  (10, 'King', 'Stephen', 4),
  (11, 'Coelho', 'Paulo', 8),
  (12, 'Kafka', 'Franz', 6),
  (13, 'Dickens', 'Charles', 9),
  (14, 'Shakespeare', 'William', 9),
  (15, 'Proust', 'Marcel', 0),
  (16, 'Eco', 'Umberto', 1),
  (17, 'Cervantes', 'Miguel', 3),
  (18, 'Zola', 'Émile', 0),
  (19, 'Asimov', 'Isaac', 4);
